CREATE TABLE `pulse`.`pulsenew` (
  `idpulsenew` INT NOT NULL AUTO_INCREMENT,
  `week` INT NOT NULL,
  `collection_dates` VARCHAR(255) NOT NULL,
  `xtab_var` VARCHAR(255) NOT NULL,
  `xtab_val` INT NOT NULL,
  `cbsa_title` VARCHAR(255) NULL,
  `q_var` VARCHAR(255) NOT NULL,
  `q_var_label` VARCHAR(255) NOT NULL,
  `q_val` VARCHAR(255) NOT NULL,
  `q_val_label` VARCHAR(255) NULL,
  `pweight` DOUBLE NOT NULL,
  `pweight_lower` DOUBLE NOT NULL,
  `pweight_upper` DOUBLE NOT NULL,
  `pweight_share` DOUBLE NOT NULL,
  `pweight_share_lower` DOUBLE NOT NULL,
  `pweight_share_upper` DOUBLE NOT NULL,
  `hweight` DOUBLE NOT NULL,
  `hweight_lower` DOUBLE NOT NULL,
  `hweight_upper` DOUBLE NOT NULL,
  `hweight_share` DOUBLE NOT NULL,
  `hweight_share_lower` DOUBLE NOT NULL,
  `hweight_share_upper` DOUBLE NOT NULL,
  PRIMARY KEY (`idpulsenew`),
  UNIQUE INDEX `idpulsenew_UNIQUE` (`idpulsenew` ASC) VISIBLE);
